import type { Item } from "./types";

export const seedItems: Item[] = [
  {
    id: "s1",
    name: "Air Jordan 4 Bred Reimagined",
    brand: "Jordan",
    category: "sneakers",
    size: "EU 43",
    buyPrice: 220,
    buyDate: "2026-01-12",
    marketPrice: 320,
    status: "stock",
  },
  {
    id: "s2",
    name: "Dior B30",
    brand: "Dior",
    category: "sneakers",
    size: "EU 42",
    buyPrice: 750,
    buyDate: "2026-02-04",
    marketPrice: 980,
    status: "listed",
    platform: "Vinted",
  },
  {
    id: "s3",
    name: "Travis Scott Jordan 1 Low OG",
    brand: "Jordan",
    category: "sneakers",
    size: "EU 42.5",
    buyPrice: 180,
    buyDate: "2025-09-20",
    marketPrice: 0,
    status: "sold",
    sellPrice: 420,
    sellDate: "2025-11-08",
    platform: "StockX",
    feesPercent: 12,
  },
  {
    id: "s4",
    name: "Supreme Box Logo Hoodie FW23",
    brand: "Supreme",
    category: "streetwear",
    buyPrice: 320,
    buyDate: "2025-12-01",
    marketPrice: 0,
    status: "sold",
    sellPrice: 540,
    sellDate: "2026-01-30",
    platform: "Vinted",
    feesPercent: 5,
  },
  {
    id: "s5",
    name: "Corteiz Alcatraz Tracksuit",
    brand: "Corteiz",
    category: "streetwear",
    buyPrice: 180,
    buyDate: "2026-02-14",
    marketPrice: 260,
    status: "stock",
  },
  {
    id: "s6",
    name: "New Balance 1906R Protection Pack",
    brand: "New Balance",
    category: "sneakers",
    size: "EU 43",
    buyPrice: 150,
    buyDate: "2026-03-02",
    marketPrice: 210,
    status: "stock",
  },
  {
    id: "s7",
    name: "Stüssy 8 Ball Crewneck",
    brand: "Stüssy",
    category: "streetwear",
    buyPrice: 110,
    buyDate: "2025-10-15",
    marketPrice: 0,
    status: "sold",
    sellPrice: 175,
    sellDate: "2025-12-12",
    platform: "Vinted",
    feesPercent: 5,
  },
  {
    id: "s8",
    name: "Nike SB Dunk Low Pro Black",
    brand: "Nike",
    category: "sneakers",
    size: "EU 44",
    buyPrice: 130,
    buyDate: "2026-03-22",
    marketPrice: 200,
    status: "listed",
    platform: "StockX",
  },
];
